// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mahalanobis_c
double mahalanobis_c(double y, double mu, double sigma);
RcppExport SEXP _MRT_mahalanobis_c(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mahalanobis_c(y, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// norm_c
double norm_c(double y, double mu, double sigma);
RcppExport SEXP _MRT_norm_c(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(norm_c(y, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// MMEst
Rcpp::List MMEst(const arma::vec& y, int g, double tol, int max_iter);
RcppExport SEXP _MRT_MMEst(SEXP ySEXP, SEXP gSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type g(gSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(MMEst(y, g, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MRT_mahalanobis_c", (DL_FUNC) &_MRT_mahalanobis_c, 3},
    {"_MRT_norm_c", (DL_FUNC) &_MRT_norm_c, 3},
    {"_MRT_MMEst", (DL_FUNC) &_MRT_MMEst, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_MRT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
