# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@importFrom Rcpp sourceCpp
#'@useDynLib MRT
NULL

mahalanobis_c <- function(y, mu, sigma) {
    .Call('_MRT_mahalanobis_c', PACKAGE = 'MRT', y, mu, sigma)
}

norm_c <- function(y, mu, sigma) {
    .Call('_MRT_norm_c', PACKAGE = 'MRT', y, mu, sigma)
}

#'@export
MMEst <- function(y, g = 1L, tol = 0.00001, max_iter = 100L) {
    .Call('_MRT_MMEst', PACKAGE = 'MRT', y, g, tol, max_iter)
}

